---
kind: pipeline
name: default

steps:
- name: set version in Cargo.toml
  image: rust:slim
  commands:
  - echo "Setting Cargo.toml to version $DRONE_TAG:"
  - sed -i -e "s/99\.99\.9/$(echo $DRONE_TAG | tr -d 'v')/" Cargo.toml
  - cat Cargo.toml
  when:
    event: tag

- name: build for x86_64
  image: rust:alpine
  commands:
  - apk add --no-cache make gcc g++
  - cargo build --release

- name: build for armv7l
  image: rust:slim
  commands:
  - apt-get update
  - apt-get install -y make gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
  - rustup target add armv7-unknown-linux-gnueabihf
  - cargo build --release --target armv7-unknown-linux-gnueabihf

- name: build for Windows
  image: rust:slim
  commands:
  - apt-get update
  - apt-get install -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
  - rustup target add x86_64-pc-windows-gnu
  - cargo build --release --target x86_64-pc-windows-gnu

- name: prepare release
  image: rust:slim
  commands:
  - mkdir target/_release
  - cp target/release/netio                               target/_release/netio-x86_64
  - cp target/armv7-unknown-linux-gnueabihf/release/netio target/_release/netio-armv7l
  - cp target/x86_64-pc-windows-gnu/release/netio.exe     target/_release/netio.exe
  when:
    event: tag

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github-token
    files:
      - target/_release/netio-x86_64
      - target/_release/netio-armv7l
      - target/_release/netio.exe
    checksum:
      - sha256
  when:
    event: tag
---
kind: signature
hmac: 9da0b47af204c93c633b04f8891647ac4eaa746dde62fec3a82bf119cc7ca115

...
