---
kind: pipeline
name: default

steps:
- name: build for Linux
  image: rust:latest
  commands:
  - cargo build --release

- name: build for Windows
  image: rust:slim
  commands:
  - apt-get update
  - apt-get install -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
  - rustup target add x86_64-pc-windows-gnu
  - cargo build --release --target x86_64-pc-windows-gnu

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github-token
    files:
      - target/release/netio
      - target/x86_64-pc-windows-gnu/release/netio.exe
    checksum:
      - sha256
  when:
    event: tag
---
kind: signature
hmac: d42fcf6b20b64df00975ce52c43f014ef2f31aa42826ef809c1bcfdcd3b14917

...
